apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: spotify-stats
  labels:
    app: spotify-stats
data:
  SERVER_PORT: "8080"
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: spotify
  SPOTIFY_SCOPES: user-read-recently-played playlist-read-private
  SPOTIFY_REDIRECT_URI: http://localhost:8080/api/callback
