apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: spotify-stats
  labels:
    app: spotify-stats
stringData:
  APP_JWT_SECRET: super-secret-jwt
  APP_CRYPTO_PASSWORD: super-crypto-password
  APP_CRYPTO_SALT: super-crypto-salt
  DB_USER: spotify_user
  DB_PASSWORD: spotify_password
  MYSQL_ROOT_PASSWORD: root_password
  SPOTIFY_CLIENT_ID: spotify_client_id
  SPOTIFY_CLIENT_SECRET: spotify_client_secret
