apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: spotify-stats
  labels:
    app: spotify-stats
stringData:
  APP_JWT_SECRET: zrsrc6EAg2BZfhR4SxFQPY8N6R1N9Nj+vbtw9aFfMfM=
  APP_CRYPTO_PASSWORD: super-crypto-password
  APP_CRYPTO_SALT: a4f93c10b1e8a7f2
  DB_USER: spotify_user
  DB_PASSWORD: spotify_password
  MYSQL_ROOT_PASSWORD: root_password
  SPOTIFY_CLIENT_ID: spotify_client_id
  SPOTIFY_CLIENT_SECRET: spotify_client_secret

# Das hier sind testdaten die aber funktionieren sollten um Funktionalit√§t zu testen
# APP_JWT_SECRET= muss 32 Zeichen lang sein