apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: spotify-stats
  labels:
    app: spotify-stats
spec:
  type: ClusterIP
  selector:
    app: spotify-stats
    tier: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  