apiVersion: v1
kind: Service
metadata:
  name: spotify-app-service
  namespace: spotify-stats
  labels:
    app: spotify-stats
spec:
  type: ClusterIP
  selector:
    app: spotify-stats
    tier: app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  